#!/bin/bash

prefix=$1
cur_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

perl $cur_dir/mcscan_to_size_count.pl $prefix
cat $prefix.syn_block |sort -k2,2 -k3,3n >$prefix.syn_block.sorted
perl $cur_dir/join.pl $prefix.syn_block.sorted >$prefix.syn_block.sorted.join
perl $cur_dir/sum.pl $prefix.syn_block.sorted.join
