rename Abpre	Abrus_precatorius  *
rename Aeeve	Aeschynomene_evenia  *
rename Amnan	Ammopiptanthus_nanus  *
rename Amedg	Amphicarpaea_edgeworthii  *
rename Anine	Andira_inermis  *
rename Anbra	Angylocalyx_braunii  *
rename Aqcoe	Aquilegia_coerulea  *
rename Artha	Arabidopsis_thaliana  *
rename Ardur	Arachis_duranensis  *
rename Aripa	Arachis_ipaensis  *
rename Arfim	Aristolochia_fimbriata  *
rename Assin	Astragalus_sinicus  *
rename Avcar	Averrhoa_carambola  *
rename Bavar	Bauhinia_variegata  *
rename Bemas	Begonia_masoniana  *
rename Cacaj	Cajanus_cajan  *
rename Casat	Cannabis_sativa  *
rename Cavim	Carpinus_viminea  *
rename Caaus	Castanospermum_australe  *
rename Cecan	Cercis_canadensis  *
rename Cechi	Cercis_chinensis  *
rename Chfas	Chamaecrista_fasciculata  *
rename Chpum	Chamaecrista_pumila  *
rename Ciari	Cicer_arietinum  *
rename Ciret	Cicer_reticulatum  *
rename Clpla	Cladrastis_platycarpa  *
rename Daodo	Dalbergia_odorifera  *
rename Daglo	Datisca_glomerata  *
rename Disch	Dialium_schlechtneri  *
rename Diala	Dipteryx_alata  *
rename Diodo	Dipteryx_odorata  *
rename Duorc	Duparquetia_orchidacea  *
rename Epfal	Eperua_falcata  *
rename Faalb	Faidherbia_albida  *
rename Gllat	Glycine_latifolia  *
rename Glsoj	Glycine_soja  *
rename Glura	Glycyrrhiza_uralensis  *
rename Gomar	Goniorrhachis_marginata  *
rename Lapur	Lablab_purpureus  *
rename Lojap	Lotus_japonicus  *
rename Lualb	Lupinus_albus  *
rename Luang	Lupinus_angustifolius  *
rename Lyrho	Lysidice_rhodostegia  *
rename Mepol	Medicago_polymorpha  *
rename Merut	Medicago_ruthenica  *
rename Metru	Medicago_truncatula  *
rename Mealb	Melilotus_albus  *
rename Mipud	Mimosa_pudica  *
rename Myrub	Myrica_rubra  *
rename Nisch	Nissolia_schottii  *
rename Orsat	Oryza_sativa  *
rename Paand	Parasponia_andersonii  *
rename Phacu	Phaseolus_acutifolius  *
rename Phlun	Phaseolus_lunatus  *
rename Phvul	Phaseolus_vulgaris  *
rename Pisat	Pisum_sativum  *
rename Potat	Polygala_tatarinowii  *
rename Potri	Populus_trichocarpa  *
rename Ptema	Pterodon_emarginatus  *
rename Pumon	Pueraria_montana  *
rename Sesep	Senna_septemtrionalis  *
rename Setor	Senna_tora  *
rename Sigla	Sindora_glabra  *
rename Spsub	Spatholobus_suberectus  *
rename Stjap	Styphnolobium_japonicum  *
rename Trpra	Trifolium_pratense  *
rename Trsub	Trifolium_subterraneum  *
rename Umlis	Umtiza_listeriana  *
rename Viang	Vigna_angularis  *
rename Vimun	Vigna_mungo  *
rename Virad	Vigna_radiata  *
rename Visub	Vigna_subterranea  *
rename Vitri	Vigna_trilobata  *
rename Viung	Vigna_unguiculata  *
rename Vivin	Vitis_vinifera  *
rename Zeins	Zenia_insignis  *
rename Zospl	Zollernia_splendens  *
