"""
rna-seq relevant utils
"""
from collections import OrderedDict, defaultdict

from iga.apps.base import emain, get_prefix, logger
import pandas as pd
#import numpy as np

from iga.plot.ggplot import pheatmap


def plot_exp_heatmap(table=None):
    """
    plot heatmap with merged table generated by merge_exp_table
    :param table:
    :return:
    """
    #First removing unrelated fields
    # table2 = table + ".tmp"
    # buff = ''
    # with open(table) as fh:
    #
    #     for i, line in enumerate(fh):
    #         mylist = line.rstrip().split('\t')
    #         if i == 0:
    #             new_list = mylist[6:]
    #             new_line = "\t" + "\t".join(new_list).rstrip() + "\n"
    #         else:
    #             new_list = [mylist[0]] + mylist[6:]
    #             new_line = "\t".join(new_list).rstrip() + "\n"
    #         buff += new_line
    # with open(table2, 'w') as fh:
    #     fh.write(buff)
    pheatmap(table, main="Expression Heatmap")
    return 0


def remove_dup_table(table=None):
    tpm_dict = defaultdict(float)
    with open(table) as fh:
        for line in fh:
            mylist = line.rstrip().split()
            try:
                tpm_dict[mylist[0]] += float(mylist[-1])
            except ValueError:
                logger.warning(line)
                continue
    new_table = table + ".uniq"
    with open(new_table) as fh:
        fh.write("Gene ID\tTPM\n")
        for k in tpm_dict:
            fh.write("{}\t{}\n".format(k, tpm_dict[k]))
    return new_table

def merge_exp_table(tables=None):
    """
    Merge expression table produced by stringtie into one with TPM
    :param tables:
    :return:
    """
    sample_list = []
    gene_dict = []
    z = pd.DataFrame()
    # 'Gene Name', 'Reference', 'Strand', 'Start', 'End',
    sub_list = ['Gene ID', 'TPM']
    for i, t in enumerate(tables):
        new_table = remove_dup_table(t)
        this_df = pd.read_table(new_table, sep='\t')
        logger.warning(this_df.columns)
        sub_df = this_df[list(sub_list)]
#        sub_df = sub_df.groupby('Gene ID').TPM.apply(lambda g: g.nlargest(2).sum())
        #Now change subdf's column name
        t_prefix = get_prefix(t)
        new_sublist = sub_list.copy()
        new_sublist[new_sublist.index('TPM')] = t_prefix
        sub_df.columns = new_sublist
        if i == 0:
            z = sub_df
        else:
            z = z.merge(sub_df, left_on=sub_list[0],
                    right_on=sub_list[0], how='outer')
        #sample_list.append(get_prefix(t))
    prev_column = list(z.columns)
    prev_column[0] = ""
    z.columns = prev_column
    z.to_csv('merged_expression.txt', sep="\t", index=False, na_rep='0.0')
    return z


if __name__ == "__main__":
    emain()
